### ISSUE TITLE
Bower publishing

### ISSUE THREAD

**Issue by vitaliy-bobrov** [dixonandmoe/rellax#1]
Could you publish your library to the bower and/or npm.

**Comment by moeamaya** [comment]
@vitaliy-bobrov The library is still a bit buggy. I'm planning on publishing to both once the library is usable  without my direct input. We'll be using this in production on https://dixonandmoe.com/ and that will require us to find all the bugs and write better docs!

**Comment by vitaliy-bobrov** [comment]
Ok, I've tried to optimize your implementation, I used requestAnimationFrame for position update. Also I've tried to wrote it with es2015 + babel. I like you idea to use translate3d it shows good performance.
If you interested I'll upload my workarounds on github)

**Comment by moeamaya** [comment]
Yes I would love to see it! I'm especially curious what your rAF implementation looks like.

I decided against es6 since I wanted to control file size and not have the code transpiled. But I can be persuaded if the file size stays relatively small.

**Comment by KasperAndersson** [comment]
+1 for npm publish

**Comment by moeamaya** [comment]
@KasperAndersson @vitaliy-bobrov This initial version is published on npm as 'rellax'. Thanks for the motivation!

**Comment by KasperAndersson** [comment]
@moeamaya Nice one!
