### ISSUE TITLE
How to restrict parallax animation only within a container?

### ISSUE THREAD

**Issue by daviedR** [dixonandmoe/rellax#102]
Hi Dixon and Moe,

How to set a container for the parallax element? Currently the parallax elements is animated relative to document height. So if I have a parallax elements in the bottom of my page, it would be already animated even if I am still view the top part of my page. This cause my parallax element stray away too far from its original position.

Is there a way that the animation would only work when the `window.scrollTop` value touch my defined container for that parallax element?

If it's not supported yet in Rellax, I think this is a very crucial issue, and we need to add this option. I saw other libraries also have this option.

Thanks for the great library btw!

**Comment by moeamaya** [comment]
Should work with the latest version I just merged.

**Comment by zakgreene** [comment]
The elements I set don't appear to be behaving the way @daviedR describes. Their `transform()` properties are changing on scroll even when they're offscreen. Am I missing something? I agree that this would be very helpful to improve performance and to help me position the starting point of the elements more accurately.

**Comment by jaydickinson** [comment]
Any documentation on this?
