### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by shrpne** [dixonandmoe/rellax#105]
Please consider adding changelog: [keepachangelog.com](https://keepachangelog.com)

**Comment by moeamaya** [comment]
Agree, been `npm publish`-ing a lot of changes without any documentation

**Comment by moeamaya** [comment]
@shrpne Added a changelog to the README starting with v1.7.0

**Comment by shrpne** [comment]
@moeamaya Thank you! I also want to notice, that usually changelogs are placed to the separate `CHANGELOG.md` file
