### ISSUE TITLE
transform3d added multiple times to elements

### ISSUE THREAD

**Issue by DhruveOnMars** [dixonandmoe/rellax#113]
Hey,

I have the following to initialise the plugin in my angular component

`var rellax = new Rellax('.parall--text');`

however for every instance of that class, it adds that number of translate3d to each item.

So, at the moment I have two `.parall--text` items, and so my transforms look like this: `translate3d(0px, 34px, 5px) translate3d(0px, 0px, 5px)`

It also does listen to attributes I set via the html, such as the speed or z-index.

Any help with this is appreciated

**Comment by moeamaya** [comment]
Thanks for the issue. I'm not sure I can recreate this since I'm not an Angular user. So far no one else has reported this using vanilla js, react or vue, so I'm closing this for now.

**Comment by michaelpumo** [comment]
I am also getting this issue in Vue JS.

If I have more than one instance of `new Rellax()` it appears to add the amount of transforms equal to the amount of instances there are created.

It's very strange as each component is encapsulated.

**Comment by turnstylerj** [comment]
Figured I'd add to this thread in case someone else arrives here after Googling the issue - I was experiencing this problem in a vanilla JavaScript project and found my issue was I was mistakenly initting Rellax twice on the same element. Add a log when you're initiating Rellax to check this isn't happening!
