### ISSUE TITLE
Max number of elements that .rellax class can be applied to?

### ISSUE THREAD

**Issue by golars497** [dixonandmoe/rellax#117]
Hi,

Context: I am experimenting as to how many elements I can apply parallax to using rellax.js.
So basically I have this simple home page, where I create this tile grid
![grid](https://user-images.githubusercontent.com/16651326/39669161-3ba3f23a-50dc-11e8-84ab-3e684adc34b2.png)

For every tile, a div is generated - The background-img is set to a tile image (only 3 different images used: black tile, pink tile and blue tile).
Each of these divs all share these properties:
  width: 100%;
  height: 900px;
  position: fixed;
  left: 0;
  top: 0;
  background-repeat: no-repeat;
  background-size: 70px !important;

In total, about 1120 divs are created. The only divs that I assigned the .rellax class to are **only the 3 pink tiles** (got a little covered by the menu bar on the first image).
The rendering would just be completely broken (the menu even disappears):
![broken-grid](https://user-images.githubusercontent.com/16651326/39669222-69e62022-50dd-11e8-8142-7739c6aec943.JPG)

What I did try to do was reduce the number of tile divs, and still only apply parallax to the 3 pink tiles. When I reduced it to 4 rows (112 tiles) the parallax functions perfectly:
![better](https://user-images.githubusercontent.com/16651326/39669263-be7a2e0c-50de-11e8-8dde-d60b7e38a22a.JPG)
However, using generating more than 112 tile divs would just break the rendering completely.

Just wondering if this a framework limitation or browser (chrome) limitation? and if not, there has to be some issue with my code (I've only added the .rellax class to the 3 pink tiles. No data attributes, and I also only call the "var rellax = new Rellax('.rellax');" after all the tiles have loaded).

I am happy to provide any missing information,

Any help would be appreciated - Many Thanks!

**Comment by golars497** [comment]
UPDATE: I found that instead of using <div> for each tile and assigning the background-image property, it worked fine if I used the <img> element and link reference the tile img via src.

**Comment by moeamaya** [comment]
Sorry missed this one, but great that you found a solution!!

I'd love to see the final result when you get a chance to send it over.
