### ISSUE TITLE
Mobile Speed? ... data-rellax-media-mobile-speed="-10"

### ISSUE THREAD

**Issue by oneezy** [dixonandmoe/rellax#121]
It would be nice if there were an easy way to control the speed for different devices. Do you guys think this would be a good idea?

If so, I imagine it would look something like this:

```
<div class="rellax" 
     data-rellax-mobile-speed="-6" 
     data-rellax-tablet-speed="-8" 
     data-rellax-desktop-speed="-10">
</div>

<script>
  var rellax = new Rellax('.rellax', {
     mobile: 0,
     tablet: 769,
     desktop: 1025
  });
</script>
```

**Comment by moeamaya** [comment]
Love this idea!

Don't have any bandwidth to work on it but happy to merge if someone wants to create a PR
