### ISSUE TITLE
Use Smooth-ScrollBar & Rellax Together

### ISSUE THREAD

**Issue by sadeghbarati** [dixonandmoe/rellax#122]
I'm using `smooth-scrollbar` effect with this repository https://idiotwu.github.io/smooth-scrollbar/

when smooth-scroll init force an element with `fake height` and `fixed` position for `SmoothScroll effect`

`rellax` parallax doesn't work 

> when we have `fixed element`

any idea ?

**Comment by avitorio** [comment]
Hi @riiccardo,

I've been struggling with the same challenge. Did you manage to get around this?

Please, let me know. I'll keep on trying and will put the solution here if I find one!

Cheers!

**Comment by therealedsheenan** [comment]
I'm also having the same dilemma.  Technically, since the  smooth scroll container is set to `fixed`, rellax library cannot get the `scroll` position value(which is used for the parallex effect on `rellax` side).

**Comment by avitorio** [comment]
Hi guys,

I found this repository. It's from an agency: https://locomotive.ca
It seems they managed to do it:

https://github.com/locomotivemtl/locomotive-scroll

Hope this helps!

**Comment by piyushwalia** [comment]
Found this repository which works with both rellax and smooth scrollbar
[https://github.com/BiserStoilov/scroll-animations](url)
