### ISSUE TITLE
Supporting horizontal parallax effect(Even on vertical scroll)

### ISSUE THREAD

**Issue by therealedsheenan** [dixonandmoe/rellax#123]
Is there any way to set parallax effect horizontally even when scrolling vertically?

So, elements will be moving from `left - right` or `right - left`...

**Comment by moeamaya** [comment]
Part of 2.0

**Comment by notorigine** [comment]
Any ETA on 2.0? Great lib btw! 👍

**Comment by rosebucket** [comment]
has work on this been started? i'd be down to try to contribute this feature but depends on if you were expecting it to be a major major change

**Comment by spenncerr** [comment]
Hey @moeamaya should we expect v2 this year? :) Asking for a friend.

**Comment by Your3Wishes** [comment]
I opened a pull request with this functionality. It allows you to specify movement direction for both vertical and horizontal scrolling. It even allows you to specify both X and Y movement during scrolling (aka diagonal movement). 
Also includes options for defining horizontal and vertical movement speed for each item, as well as min/max bounds in both directions.

https://github.com/dixonandmoe/rellax/pull/176

**Comment by mattrittman** [comment]
Just curious, if there is any development on this?

**Comment by peiris** [comment]
I'm also waiting for this. It would be a great addition. any news?

**Comment by pickyuptruck** [comment]
+1 for horizontal parallax

**Comment by joehdevwp** [comment]
+1 for horizontal parallax  (elements move horizontally while user scrolls vertically)

**Comment by MizuBishi** [comment]
+1 for horizontal parallax (elements move horizontally while user scrolls vertically)

**Comment by Ramphy0x90** [comment]
+1 for horizontal parallax (elements move horizontally while user scrolls vertically)

**Comment by SeckinSozen** [comment]
+1 for horizontal parallax (elements move horizontally while user scrolls vertically)

**Comment by SalhiYassine** [comment]
+1 for horizontal parallax (elements move horizontally while user scrolls vertically)

**Comment by Your3Wishes** [comment]
For anyone coming back to this issue: this feature was merged in a long time ago and is supported. Not sure why this issue is still marked open.

**Comment by annafractuous** [comment]
**To achieve horizontal parallax on vertical scroll**

1) add `horizontal: true` to your Rellax instance parameters
2) add `data-rellax-vertical-scroll-axis="x"` to your rellax HTML elements

e.g.

JS:
```
var rellax = new Rellax('.rellax', { horizontal: true });
```

HTML:
```
<div class="rellax" data-rellax-vertical-scroll-axis="x" data-rellax-speed="12" data-rellax-mobile-speed="14"></div>
<div class="rellax" data-rellax-vertical-scroll-axis="x" data-rellax-speed="9" data-rellax-mobile-speed="11"></div>
```

see examples here: https://github.com/dixonandmoe/rellax/blob/master/tests/directions.html
