### ISSUE TITLE
Stop parallax 

### ISSUE THREAD

**Issue by NasJoSef** [dixonandmoe/rellax#124]
Hi there, 

Thank you for sharing this wonderful plugin, i want just to know if there an option to stop parallax(Animation) when div's (2) are in the whole div parent.

Here the exemple : https://codepen.io/nassimseffar/pen/wEWXQX
Thank you guys.

**Comment by moeamaya** [comment]
This would have to be managed on your end, but honestly I don't think there's a clean way to do it. 

I'm going to close this though since it's kinda an edge case and not a feature we'll be adding to the library.
