### ISSUE TITLE
Angular and typescript

### ISSUE THREAD

**Issue by slzr** [dixonandmoe/rellax#127]
Is there a way to integrate this plugin in `Angular `with `Typescript `or something like that?
in the readme an example is shown for `React`, there is an equivalent for `Angular`, maybe a way to implement it in a directive?

**Comment by moeamaya** [comment]
I'll leave this open for a bit, but from the few emails I've received a lot of folks have gotten this to work with Angular.

**Comment by slzr** [comment]
@moeamaya any update?

**Comment by mehdi753** [comment]
hello, i maybe am a little late, but hey, better late then ever right ? 
anyways here's what you should do:
1) install npm: npm i rellax
2)open angular.json and under scripts and add the relative path where it has been installed, mine is:
 "./node_modules/rellax/rellax.min.js"
3)in you component .ts add the following code:

`declare var Rellax : any;
export class yourComponent implements OnInit {
  ngOnInit() {
    var rellax = new Rellax('.rellax');
  }
}`
4)finally add the rellax class to the element, and everything should work just fine
NOTE: in case you don't know after completing step 2 if the localhost server is running u should shut it down so the next time you run ng serve the rellax script will be compiled.
NOTE 2: `declare var Rellax : any;` should be under the imports
