### ISSUE TITLE
Vue + NUXT Integration

### ISSUE THREAD

**Issue by Britzer** [dixonandmoe/rellax#130]
Being that Rellax is vanilla I figured it would be a great addition to my Vue + NUXT project.

I've created a plugin like you would any other library you're trying to get into your project (rellax.js):
```
import Rellax from 'rellax';
import Vue from 'vue';

Vue.prototype.$rellax = () => {
    return {
        Rellax
    }
}
```
In my config file I have included it in my Build configuration with the rest of my plugins (nuxt.config.js):
```
plugins: [
    ...
    { src: '~/plugins/rellax.js', ssr: false}
    ...
]
```
Lastly, in my component I'm calling this.$rellax('.rellax') on mounted. And have 3 different div'd with the class name of "rellax":
```
<template lang="pug">
    .trucks-alt
        slide-header.rellax
        parallaxer.rellax
        .placeholder.rellax 
</template>

export default {
    name: 'page-name',
    ...
    mounted () {
        console.log(this.$rellax());
        this.$rellax('.rellax');
    },
    ...
}
```
I went ahead and log'd out "this.$rellax" and it finds the function(el, options). Not sure what I'm doing wrong...

**Comment by raphaelaitelalim** [comment]
Hey, 

I use rellax too on a Vue + Nuxt project. Just import on your component like this : 

`import Rellax from "rellax";`

and for example in mounted() method : 

`var rellax = new Rellax(".rellax", {options});`

or by adding class in html : 

`<div class="rellax">`

Hope this helps !

**Comment by moeamaya** [comment]
Thanks for your help @raphaelaitelalim
