### ISSUE TITLE
Perfomance issues on some iOS devices

### ISSUE THREAD

**Issue by nixolas1** [dixonandmoe/rellax#133]
Hi, I like the plugin, and it runs smoothly on most devices, but on a few iOS devices the scrolling on the whole page becomes laggy with Rellax enabled.

Affected devices: 
- iPad Air 2
- iPhone 5s
- iPhone 6s

**Comment by moeamaya** [comment]
We've done extensive testing on an iphone 5s. As long as you aren't using too many rellax elements that are images, it should work great!

Test the demo site on one of your devices.
