### ISSUE TITLE
Other Transforms

### ISSUE THREAD

**Issue by sanderjson** [dixonandmoe/rellax#135]
I want to apply rellax to multiple elements on the page but I want them to keep their own transforms for absolute layouts. What is the correct method for this?

var rellax = new Rellax('.class', {
   transform: 'rotate(45deg)',
   replace: true
 });

**Comment by Tibo46** [comment]
What you can do is apply for example the rotate to your child element, and the parallax effect to the parent.
`<div class="rellax" data-rellax-speed="1">
          <img src="assets/img/products/products-2.png" class="product product-1" />
        </div>`

`.product {
  position: absolute;
  width: 250px;
}
.product-1 {
  right: 6rem;
  top: 3rem;
  transform: rotate(-45deg);
}`

**Comment by sanderjson** [comment]
Assume this works
