### ISSUE TITLE
Page reload gets wrong position of parallax element

### ISSUE THREAD

**Issue by julianorth** [dixonandmoe/rellax#138]
When i'm at the bottom of the page and reload it, at least in chrome i will be at the bottom of the page even after reload (scroll position is cached). So when i have a rellax element on the top of the page and now (after reload) scroll from bot to top the parallax position will be wrong.
Tried to use something like this in jquery document.ready $(window).scrollTop(0); to force the browser to scroll top on reload but it did not bring the desired result.

Any idea ?

**Comment by P3t3r6** [comment]
Hi! Could you take a look at #52 and see if that solution works for you? Thanks.

**Comment by p-realinho** [comment]
Hi! Could you take a look at #52 and see if that solution works for you? Thanks.

**Comment by ekozelkova** [comment]
Thank you Pedro for referencing at this issue every time, it helped me now :D
