### ISSUE TITLE
All axes are overridden inline by rellax (closed)

### ISSUE THREAD

**Issue by Jugibur** [dixonandmoe/rellax#144]
EDIT: Sorry, I was wrong: Each transform command overrides another one, so no change to left my transform property untouched. Only with Javascript this behavior could be changed.
-------
I have transformed an object horizontally.
Unfortunately, rellax is override all axes 
i.e.: 
`transform: translate3d(0px, -419px, 0px);`
Why not just write the used axe, i.e. translateY() 

Currently I must use an !important to keep my own translations intact.

**Comment by leleoalmeida** [comment]
Same thing happening to me with `rotateZ()`, but using `!important` is overriding rellax for me.

**Comment by Jugibur** [comment]
Yes, unfortunately the specification of CSS doesn't allow setting separate transform commands.
