### ISSUE TITLE
Wrong link in demo page

### ISSUE THREAD

**Issue by p-realinho** [dixonandmoe/rellax#147]
The link for "Service List", at the bottom, in the [demo page](https://dixonandmoe.com/rellax/) is linking to `https://cssgradient.io/` instead of `https://servicelist.io/`.

I was gonna fix it, but I can't seem to find it in the repo.

**Comment by moeamaya** [comment]
Thanks @p-realinho. Fixed it! (it's in the private dixonandmoe.com repo)
