### ISSUE TITLE
Non-functional configuration with Rellax

### ISSUE THREAD

**Issue by sergeymorkovkin** [dixonandmoe/rellax#149]
1. Set wrapper to parent element node
2. Set relativeToWrapper to false
3. Nothing moves

**Comment by shrpne** [comment]
Your wrapper should have scrollbar and you wrapper `scrollTop` should change when scrolling, is it?

**Comment by sergeymorkovkin** [comment]
No, my wrapper has no scrollbar and it scroll as a part of the page.

**Comment by shrpne** [comment]
Then you should set `wrapper: null` or `relativeToWrapper: true` to make it work.
