### ISSUE TITLE
Demo Website broken for mobile (Chrome/Safari)

### ISSUE THREAD

**Issue by starpause** [dixonandmoe/rellax#18]
Is this library intended for use on mobile? The demo page is broken when I view it on Chrome Android or Safari iOS. Thanks!

![screenshot_2016-10-06-11-18-16](https://cloud.githubusercontent.com/assets/408953/19165047/27779280-8bb7-11e6-974e-85ed5d0b8bad.png)

**Comment by moeamaya** [comment]
Just pushed a fix to the main website: https://dixonandmoe.com/rellax/. Will be updating the demo site very soon!

**Comment by moeamaya** [comment]
Fixed with the recent 1.0 push

**Comment by rickvian** [comment]
hi, i checked the demo files index.html, still same as screenshot above @starpause
