### ISSUE TITLE
Left-Right Parallax?

### ISSUE THREAD

**Issue by zaxwebs** [dixonandmoe/rellax#186]
Any way to set the direction to be horizontal instead of vertical? If not, could this be added?

**Comment by zaxwebs** [comment]
Clarification: on vertical scroll.

**Comment by zoh48gz04** [comment]
```
new Rellax('.rellax-h', { horizontal: true })
....
<div data-rellax-vertical-speed="0" data-rellax-horizontal-speed="5" data-rellax-vertical-scroll-axis="x"></div>
```

Works for me

**Comment by ristarr11** [comment]
@zoh48gz04 solution works, but center can not be applied. Meaning, if the relax element is far below the fold, it will still get transform value changed as soon as the scroll on body starts. It seems horizontal scrolling ignores center: true and data-rellax-percentage="0.5".
I hope maybe someone has found the solution for this scenario...

**Comment by moeamaya** [comment]
We don't plan to support this one
