### ISSUE TITLE
TypeError: options is undefined

### ISSUE THREAD

**Issue by kozyrev-artem** [dixonandmoe/rellax#187]
File - rellax.js

Line - 177
if (options.breakpoints) {
   validateCustomBreakpoints();
}

When init function without options such issue appear "TypeError: options is undefined"

Init code:

import Rellax from 'rellax';
jQuery(function() {
  initParallax();
});
function initParallax() {
  jQuery('[data-parallax]').each(function() {
    new Rellax(this);
  });
}

**Comment by droach587** [comment]
This is still an issue with the Yarn/NPM module :(

**Comment by Kruemelkatze** [comment]
Still waiting for @moeamaya to either fix this or accept my PR #188 😢

In the meantime, you can mitigate this problem by just providing an empty object as options:
```javascript 
var rellax = new Rellax('.parallax', {});

```
