### ISSUE TITLE
Background Parallax Scroll?

### ISSUE THREAD

**Issue by ariona** [dixonandmoe/rellax#2]
Are you planning to implement background parallax? since the demo only show the implementation on an element postition.

**Comment by moeamaya** [comment]
@ariona We very explicitly don't use background-image in our html code because Google can't index those images. We create a <div> wrapper with overflow:hidden and put an image inside of that <div>. If you structure your code that way, you can still use Rellax!

**Comment by thedonquixotic** [comment]
I prefer this solution actually, since I'm building a theme in Wordpress, and background-image can lead to some wonky side effects. Would be nice to see an example of this in the pack though!

**Comment by Alex360hd** [comment]
It would be great to have a "background mode" that deals with background-position property to create the parallax effect. Sometimes background image is the way to go...

I would love to see that in relax to avoid to install 2 plugins to manage parallax effects.

**Comment by lachieh** [comment]
[paroller.js](https://github.com/tgomilar/paroller.js) handles both background images and DOM elements.

**Comment by brandonjp** [comment]
> We very explicitly don't use background-image in our html code because Google can't index those images. 
@moeamaya  Why do need every image to be indexed for Google Image Search?  (This is a legit question, btw. Not being snotty, just trying to learn!)  Your comment has made me analyze a few of my sites and some background images are so exclusive to the site design, I'm just trying to understand the case for why I would want those to show up in Image Search.  Does it benefit the overall site SEO maybe?
