### ISSUE TITLE
Rellax isn't working properly

### ISSUE THREAD

**Issue by humayunkabir** [dixonandmoe/rellax#203]
Device: iMac
Browsers: In Chrome, Safari, Edge(beta), Brave, there is a jumping issue. Parallax isn't smooth. But in Firefox and Tor, it's working fine and smooth. I think there is an issue related to WebKit.

I tasted the following official demo page:
[https://dixonandmoe.com/rellax/](https://dixonandmoe.com/rellax/)

Here is the screencasts:
[screencast.zip](https://github.com/dixonandmoe/rellax/files/4627423/screencast.zip)

**Comment by moeamaya** [comment]
Fixed with latest
