### ISSUE TITLE
Object.freeze() ie11

### ISSUE THREAD

**Issue by u-mulder** [dixonandmoe/rellax#21]
IE11 fails with 
![IE Fail](http://dl2.joxi.net/drive/2016/10/18/0018/0306/1204530/30/56f561e93b.jpg)
which is `argument is not an object` in English.
Happens on line `Object.freeze();`

Are you sure guys there's no need to pass object to `Object.freeze()`? 
At least for IE argument is mandatory.
Do you think everyone uses ES6?

**Comment by cfxd** [comment]
Confirming, this is an issue in IE11

![image](https://cloud.githubusercontent.com/assets/1671933/20473498/2019a19e-af8f-11e6-805a-5bb2cec94222.png)

**Comment by joshuapease** [comment]
Running into the same issue on IE. 

I haven't really dug into the source code much, so I don't know the developers original intent with Object.freeze(). But it looks like it [requires an object as an argument](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze)

I'm assuming they want to freeze the Rellax object (self)? 

Things seem to work well in IE when I make that change. If this is the correct route to go, I'd be happy to submit a Pull Request. 

```
init();
Object.freeze(self);
return self;
```

**Comment by nathanaelphilip** [comment]
@joshuapease thanks for the fix :). Saved my life!
