### ISSUE TITLE
Missing Ability to Delay Effect

### ISSUE THREAD

**Issue by Chaoste** [dixonandmoe/rellax#213]
Hi,

I'm using this plugin to move a banner image on pages slower than the following content which works nicely. But when I apply this effect on a banner at the bottom of the page, it won't work properly since it's just directly linked to the scrollTop variable but doesn't care whether my target node isn't yet in the viewport. It would be nice to give a starting position or use a scroll observer. Sot one can start the animation as soon as the element becomes visible and is independent of it's position on the page.

Greetings,
Thomas

**Comment by p-realinho** [comment]
Hey, Thomas.
Thanks for using Rellax.

Have you tried using the `center` option, or the `percentage` attribute?
Take a look at [this section](https://github.com/dixonandmoe/rellax#centering) of the readme and let me know if it solves your issue.

Thanks.

**Comment by Chaoste** [comment]
Hi,

thanks for pointing me to this feature. That's exactly what I was looking for!

Have a nice day,
Thomas
