### ISSUE TITLE
Cannot set property 'Rellax' of undefined.

### ISSUE THREAD

**Issue by btn0s** [dixonandmoe/rellax#22]
I'm getting this error coming from this line. 

https://github.com/dixonandmoe/rellax/blob/master/rellax.js#L23

Am I doing something wrong or is this common?

**Comment by moeamaya** [comment]
How are you integrating the library (npm, basic download)??

**Comment by btn0s** [comment]
I just copied the raw code and put it in a new file in my project.

**Comment by moeamaya** [comment]
Make sure you're referencing that new file before you call Rellax.

```
<script src="rellax.min.js"></script>
```
```
<script>
  // Accepts any class name
  var rellax = new Rellax('.rellax');
</script>```

Let me know if this works

**Comment by btn0s** [comment]
Okay. Currently my build system takes all the JS and puts it together in one file... do you think that might be causing the problem?

**Comment by moeamaya** [comment]
Yea that seems like a possible culprit. Make sure that you include your custom javascript the part where you wrote `var rellax = new Rellax()` after the rellax.js file. Often it's called main.js or something similar.

**Comment by moeamaya** [comment]
@btn0s Did that end up working?

**Comment by btn0s** [comment]
Hey sorry been really busy, yeah that fixed it. :)
