### ISSUE TITLE
Elements get hidden on window resize (in combination with wow.js)

### ISSUE THREAD

**Issue by michael-feh** [dixonandmoe/rellax#221]
Hey there,

i noticed that when you combine rellax.js with wow.js (for unveiling elements on scroll) elements get hidden by wow.js when you scroll to an element which makes use of both libraries and the change the window width ob the browser:

![101981976-ea4f4780-3c70-11eb-87d6-0f53c89f9ada](https://user-images.githubusercontent.com/20923682/102346353-fe5fb580-3f9e-11eb-9de3-4c5370af70d2.png)

Any Ideas?

**Comment by zangab** [comment]
because wowJS is setting `visibility: hidden`. there's no code which alters the `visibility` in the rellax library so this is not related to rellaxJS. maybe the `wow.sync()` function is helping if you call it manually on resize. 🤔

**Comment by michael-feh** [comment]
I never found a solution for this.
For now wouldn't recommend using wow and rellax in combination.
