### ISSUE TITLE
Can Rellax be used to add parallax effect on background images inside divs?

### ISSUE THREAD

**Issue by MontyHu** [dixonandmoe/rellax#223]
I didn't see an example of how to do this in the downloaded code, so wanted to ask here if Rellax is able to add the parallax effect to a background image of a div as it scrolls by in the viewport? If so, can anyone tell me how this would be done? I wasn't able to figure it out. Thanks!

**Comment by raphaelbernhart** [comment]
Hello,

yes you can create a parallax effect with rellax: [Demo](https://codepen.io/raphy02/pen/RwGEJvb)

In this issueit is described why this is not implemented by default (`background-image`): [Issue](https://github.com/dixonandmoe/rellax/issues/2#issuecomment-223372224)

Hope this helps you.

**Comment by MontyHu** [comment]
Hi Raphael, thank you very much for the Codepen demonstrating how to do this with Rellax!

**Comment by moeamaya** [comment]
Thanks @MontyHu
