### ISSUE TITLE
Page scrolls beyond content

### ISSUE THREAD

**Issue by jgresalfi** [dixonandmoe/rellax#23]
I configured Rellax on two elements: `<body>` which has an SVG texture for a background and a content div. When I add the .rellax class to the body, it doubles in height and creates a large area below the content.

What am I doing wrong??

**Comment by moeamaya** [comment]
You can't add `.rellax` to the body, you must add it to the elements that you want to change their scroll speed. 

In your case add your SVG texture as an element to the page (either a <div> or an <img>) then add the  `rellax` class to that

**Comment by jgresalfi** [comment]
Thanks for the response Moe. That was helpful.
