### ISSUE TITLE
Add bower support

### ISSUE THREAD

**Issue by thedotmack** [dixonandmoe/rellax#29]
Any thoughts on adding this to bower?

**Comment by p-realinho** [comment]
... and cdnjs, since we're on the topic? 😄

**Comment by moeamaya** [comment]
Wait, bower still is around :)

But in all seriousness, if someone wants to take on a PR that handles bower I'm all for it. Whenever we push an update to github we often forget to also push to npm, so inevitably bower would suffer the same stale code issues. 

If there's not takers in the next few weeks, we'll close this issue.

For @p-realinho cdnjs is awesome. Up for handling the push for us??

**Comment by p-realinho** [comment]
Sure! I'll try to get it done by the end of the day
