### ISSUE TITLE
Moving in the right direction?

### ISSUE THREAD

**Issue by peterwiebe** [dixonandmoe/rellax#34]
I am wondering if the behaviour changed on the direction that the parallax element is moving. I believe before the element used to move down as the user scrolled down, but now it seems to move up as the user scrolls down. 

I have two 100vh sibling divs, the first div having the rellax being applied to the background. When I scroll down, a white gap appears because of the direction of the background moving up.

**Comment by peterwiebe** [comment]
Never mind, I thought using a positive number for the speed meant it would move faster. Larger negatives makes it move faster down, larger positives makes it move faster up. Both being capped at 10.

**Comment by peterwiebe** [comment]
@moeamaya would you accept a pull request to update the example on the readme to demo the direction?

**Comment by moeamaya** [comment]
Yes absolutely! If it's not clear how it works, an updated example would be great
