### ISSUE TITLE
Relative anchoring

### ISSUE THREAD

**Issue by daltonrooney** [dixonandmoe/rellax#36]
Love this handy little library! Thanks for creating it.

We've used skrollr in the past and it has an invaluable feature I wonder if you might consider borrowing. With skrollr, you can base your element's scroll position on the main window or against another element on the page using the 'data-anchor-target' attribute. Relative anchoring keeps the relationship between two items consistent between very short pages and very long pages, for example.

Curios to know if this is a use case you've ever experienced and whether it might be added to the library at some point?

**Comment by petemcd** [comment]
+1 I'm running into this exact issue on a longer pages. Currently working around it by using negative top positions, but it would be great if it could be anchored relative to parents or other elements. 

Keep up the great work, the library is so good already!

**Comment by redpik** [comment]
:+1: 
without this feature, Rellax is completely unusable.

**Comment by moeamaya** [comment]
@daltonrooney @petemcd @redpik, while not well documented, the skrollr feature is similar to the `center: true` option in rellax.

Check out tests for sample code: https://github.com/dixonandmoe/rellax/tree/master/tests

**Comment by redpik** [comment]
wow! Thank you @moeamaya it works perfectly.
