### ISSUE TITLE
Screen height on orientation change

### ISSUE THREAD

**Issue by NeilJS** [dixonandmoe/rellax#39]
Would it be worth setting `screenY = window.innerHeight;` again within the window resize event listener? I'm thinking, when an ipad is rotated, the screen height changes.
Thanks

**Comment by twiro** [comment]
This would also help keeping parallaxed elements at the right place after resizing a browser - would love to see this implemented soon, as it's a little showstopper having to do this manually right now. But thanks a lot for this otherwise great plugin!

**Comment by vlthemes** [comment]
Solved?

**Comment by moeamaya** [comment]
Damn sorry guys missed this issue. Will take a look and try to get something out soon.

**Comment by r3oath** [comment]
Any progress on this one? If not, what's the most efficient way of doing it manually for the time being?
