### ISSUE TITLE
Scrolling issue with Safari

### ISSUE THREAD

**Issue by matthewcarleton** [dixonandmoe/rellax#41]
When scrolling to the bottom of the page the bottom is cut off.

**Comment by matthewcarleton** [comment]
Any thoughts on this? I've tried it in chrome and it works fine.

**Comment by moeamaya** [comment]
@matthewcarleton Do you still experience this?

**Comment by matthewcarleton** [comment]
@moeamaya ya I could never get it to work properly so I ditched it altogether :(

**Comment by moeamaya** [comment]
I'm not seeing any issues with the Rellax demo on Safari, so I'm gonna close this since it's probably project specific. Thanks thought Matthew
