### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by twiro** [dixonandmoe/rellax#45]
It would be great if version numbers would be used to reflect changes in the repo.

Right now all files including the readme still say "version 1.0.0" though the repo has had quite some changes since the release of the "original version 1.0.0" - using [semantic versioning](http://semver.org/) (along with github releases/tags) would be super helpful!

**Comment by connor-baer** [comment]
Using semantic versioning is also important to keep the `npm` package up to date. 
It's outdated at the moment! 🚨

**Comment by brunnolou** [comment]
It took me some time realizing that this bug #53 was caused by this.

Now my code works with this on my *package.json*:
```
"dependencies": {
    "rellax": "dixonandmoe/rellax",
```

This repo is great so please add the proper version. 👍

**Comment by moeamaya** [comment]
Hey everyone thanks for the heads up on this. I and my team never use NPM so any guidance here to make your lives easier would be great! What's the best/easiest way to handle this?

**Comment by mattclough1** [comment]
Here's a little bit from NPM on how to update: https://docs.npmjs.com/getting-started/publishing-npm-packages#updating-the-package
Pretty much just `npm version <patch/minor/major>` in the repo. Major being a +1.0.0, minor being a +0.1.0, and patch being a +0.0.1. Once you've done that, the version will be updated in your package.json, the git will be tagged, and then you can `npm publish`. 🎉

**Comment by moeamaya** [comment]
Thanks @twiro for proposing this and @mattclough1 for pointing to a solution. 

I've updated the repo to v1.1 now both in NPM and Bower. Cheers!

**Comment by mattclough1** [comment]
🎊🎉👏🎉🎊
