### ISSUE TITLE
Chrome v47 or below, in an ipad. Parallax goes white.

### ISSUE THREAD

**Issue by svegalopez** [dixonandmoe/rellax#46]
The parallax image disappears and turns white during the scrolling. After the scrolling stops, the image appears again. Only happens in ipad, have not tested in phone. Does not happen in Desktop.

**Comment by svegalopez** [comment]
@moeamaya Hello Moe. 
Just curious if you guys are going to try and fix this anytime soon ?

**Comment by moeamaya** [comment]
Hey @svegalopez apologies for the delays but our whole team is maxed out on work at the moment. Realistically we'd need someone from the communities help to get this bug fixed. Ghetto solution is to disable on mobile by adding the line we removed before launching v1.0: https://github.com/dixonandmoe/rellax/commit/03dad22800c14f734231ca48130fa8eb6b40d49d#diff-3e7be3f64be99ca4086043e1696222d6L32

**Comment by svegalopez** [comment]
@moeamaya Understood! Thanks a lot. The parallax works great otherwise.

**Comment by steveooo9** [comment]
@svegalopez Does this bug still exist?

**Comment by andreiglingeanu** [comment]
I can't experience that in the iOS simulator from OS X.
