### ISSUE TITLE
z-index request

### ISSUE THREAD

**Issue by robbisy** [dixonandmoe/rellax#51]
Hi your plugin is great but I think a data-z-index would make it better again.
What do you think ?

**Comment by Uranbold** [comment]
+1

**Comment by moeamaya** [comment]
This seems like a great suggestion! No dev time from us at the moment but go ahead and make a PR and I'm happy to merge.

**Comment by iapparatus** [comment]
+1

I'm using this with 'on hover' event and wish there was an easy way to bring an element to the top.

**Comment by fvsch** [comment]
Should this issue be closed now that PR #77 is merged?
