### ISSUE TITLE
Having problems getting rellax to do it's thing

### ISSUE THREAD

**Issue by thedonquixotic** [dixonandmoe/rellax#55]
I'm a designer learning code. Learning Wordpress also for some easy CMS integration, along with React etc. But current project is a simple Wordpress theme built from scratch. Trying to integrate rellax and having trouble getting it to work. 

I got my css all fixed so that it should work with rellax properly (everything is flex display and relative positioning) and I've got wordpress properly bundling all my JS and importing it at the end of the <body> but it doesn't appear to be running? I can confirm that script-production.js is including the rellax script

![image](https://cloud.githubusercontent.com/assets/9451726/25195349/f7ead582-2502-11e7-8482-007c0233cfdd.png)

But from what I understand it doesn't seem to be applying the transform information in the way that it should. Like shouldn't it be injecting the divs with the rellax class some transform information or something, right? It's little unclear from the documentation 

Here's a snippet of the code I'm working with:
```
 <section class="content">
        <p> <?php $field = 'case_study_intro_paragraph'; echo tag_stripped_field($field);  ?> </p>
    </section>
    <div class="image-divider rellax" data-rellax-speed="2" data-rellax-speed="4">
        <img class="image-divider rellax" data-rellax-speed="2" data-rellax-speed="4" src="https://s-media-cache-ak0.pinimg.com/564x/da/85/b3/da85b3fdcd43088765bcc70e757a0016.jpg">
    </div>
```

The php is just grabbing text from the database. I'm trying to have a static content paragraph object, interspersed with background image dividers. Also not sure if I'm supposed to put the rellax class on the img or the div containing it. I originally thought the div, but it doesn't seem to be working either way. 

Also here's a view of the final static html
![image](https://cloud.githubusercontent.com/assets/9451726/25195730/26e75e90-2504-11e7-9459-4ad46e182933.png)

Also I the settings set down at the bottom script tag, as per documentation.

**Comment by thedonquixotic** [comment]
Okay, just figured out the problem. Rellax script is being pulled in to the JS concat, but it's not being initialized. Which I think is because you have to init it using document ready or something like that right? That could be a little more explicit in the documentation, though I guess it's probably obvious to real devs. I'm just a newbie but thought this should at least be in the issues for future newbs.

**Comment by thedonquixotic** [comment]
Okay so here's how I solved this problem

Open the rellax.js file and insert this:


```
var domReady = function(callback) {
    document.readyState === "interactive" || document.readyState === "complete" ? callback() : document.addEventListener("DOMContentLoaded", callback);
};

```

And then I wrap the function like this:
```
domReady(function() {
        var Rellax = function(el, options){ <-- this is the first line of the function
```
and
```
            init();
            return self; <----this is the end of the function
        };
        
        var rellax = new Rellax('.rellax', {center: true}); <----put the call of the Rellax function here with the option settings to make sure it was called at the same time since getting both to get called seperately at the end for Wordpress was problematic. 


});

```

I also removed the AMD function because it was acting super wonky and I was entirely clear on what functionality it played. I'd really appreciate a real dev to give some feedback on my solution and what they think. If nothing else, I'd like to contribute a vanilla html, css, js version of the background images interspersed with text example test so that future users looking for this use case would have something they could go off of.

**Comment by moeamaya** [comment]
Hey thanks for your detailed description of the problem and eventual solution!

For library reasons, we probably wouldn't integrate your solution mainly because the current best practice way to include javascript is at the end of the `<body>` which negates the need for domReady since all the content has already been parsed and added. I similarly agree on removing the AMD but it's still a primary way that people add vendor javascript to their websites so it has to stay for now :(

**Comment by thedonquixotic** [comment]
@moeamaya 

Yeah the domReady thing more has to do with the quirks of WordPress since even if you put your JS in the end next to Body, it still loads other scripts before the DOM is truly ready. 

Just for my own betterment, what exactly is the purpose that AMD is playing? when you say vendor JS, do you mean that it's adding in extra stuff to help make it cross platform, or cross platform, or some combination of the two? 

I'll probably add in a vanilla example of Rellax being used for for background images, since that's probably one of the most common use cases that people are looking for with a lightweight parallax application. I'm still figuring out the CSS, but it's looking good so far!
