### ISSUE TITLE
positioning working locally but not online

### ISSUE THREAD

**Issue by GuerrillaCoder** [dixonandmoe/rellax#56]
I have got a weird issue I can't figure out.

I have made this page: https://digitalreach.online/clients/optimum/mock1.html

Locally on chrome (running in browser-sync) the words "honesty", "integrity" & "delivery" are horizontally aligned in the centre of the page and has the effect I desire where the outside words swap positions as it scrolls.

![image](https://cloud.githubusercontent.com/assets/11444395/25786183/5de9a348-3388-11e7-9d63-b0ae1bfc714a.png)

When I upload it, the exact same page now the 3 words are not lined up in the middle of the page, they are lined up at the bottom of the page and stilted in middle of page.

![image](https://cloud.githubusercontent.com/assets/11444395/25786189/72367c4a-3388-11e7-8070-129ae0866294.png)

To make it weirder in edge I get the correct effect that I get in chrome locally.

I grabbed the code from this repo in-case npm is old code but it didn't fix it.

Any idea what is going on?

**Comment by GuerrillaCoder** [comment]
I think this is related to: https://github.com/dixonandmoe/rellax/issues/53

I have discovered if I clear browser cache then refresh page at the top of page then the effect is ok.  If I scroll down the page and then hit refresh the alignment messes up.  The weird thing is that if I go back to the top of the page and hit refresh again it doesn't fix it, I have to clear the cache again and refresh at the top again to get the words to line up.

Any idea whats up?

**Comment by p-realinho** [comment]
Hi! Could you try the solution for issue #52 please?
Cause it works fine for me, unless I clear cache / refresh.

**Comment by GuerrillaCoder** [comment]
Yes, that fixed it.  For some ready using jQuery document ready event doesn't work but using window.onload does.

**Comment by p-realinho** [comment]
Nice! Glad it worked :)
That's because jQuery's document ready fires when the DOM is ready, and not the content, On the other hand, window.onload waits for the content (images in this case) to finish loading before firing.
Only then Rellax can calculate the positions correctly, because it needs to know the elements heights.
