### ISSUE TITLE
new Rellax variable question

### ISSUE THREAD

**Issue by michellomp** [dixonandmoe/rellax#57]
I want to create a widget for elementor with your parallax library . Elementor handle js files  with [scope  ](https://github.com/pojome/elementor/issues/1666)
new Rellax accepts any class name and I need to base it on $scope variable. If I put `var rellax = new Rellax(($scope.find('.rellax')));` it gives me an error cause it isn't a valid selector and if I just put` var rellax = new Rellax('.rellax');` it doesn't find the class rellax. Is there a way to make it work ?

**Comment by moeamaya** [comment]
Hi @michellomp unfortunately I've never used Elementor and I think you'll have better luck asking over at their github repo or on Stackoverflow. Closing this issue since it's specific.
