### ISSUE TITLE
Add direction option

### ISSUE THREAD

**Issue by dp-thomas** [dixonandmoe/rellax#59]
Maybe you could add an option for `direction`? Like optional `direction=-1`would reverse animations and `direction=1`would be default behaviour...

**Comment by andreiglingeanu** [comment]
Isn't that what `speed: -2/2` does?

**Comment by dp-thomas** [comment]
Guten Tag,

vielen Dank für Ihre Nachricht. 
Ich bin im Urlaub und ab dem 28. August wieder für Sie da.
Ihre Nachricht wird nicht weitergeleitet.

In dringenden Angelegenheiten kontaktieren Sie bitte meinen Kollegen Marc Oltmanns m.oltmanns@diepartments.de.

Mit freundlichen Grüßen,
Thomas Rutzer
