### ISSUE TITLE
data-rellax-speed with JS

### ISSUE THREAD

**Issue by AbrahamHalil** [dixonandmoe/rellax#60]
Hi,

how can i add `data-rellax-speed="7"` with JS

Regards
J

**Comment by radiocity** [comment]
1. Add attribute throw js using [setAttribute](https://developer.mozilla.org/en/docs/Web/API/Element/setAttribute)
2. Reinitialise rellax object

**Comment by AbrahamHalil** [comment]
Perfect,
thank you.
