### ISSUE TITLE
Where can I find detailed documentation

### ISSUE THREAD

**Issue by dkrutsko** [dixonandmoe/rellax#64]
Hey there, really great library but I'm wondering if there's documentation anywhere for the options I could pass to both the Rellax class and the data parameters. Looking at the source code I see that it supports such things as:

```js
{ speed, center, round }
{ base, top, height, speed, style, transform }
```

But I couldn't find a description of what they mean (maybe I'm blind?). Regardless, it would be nice to see in table form in the readme.

Moreover, since we're passing some parameters as data values and some as options to the class, it should just be possible to pass these parameters either way. For example, `center` and `round` should be able to be passed via data properties and `base`, `top`, etc. should be able to be passed via options to the class. Data properties would simply override any "default" options specified in the options to the class.

**Comment by moeamaya** [comment]
@dkrutsko Late reply, but updated the README to include the options that you can pass to Rellax. The second batch you mentioned `{ base, top, height, speed, style, transform }` are how we calculate the position of each element.
