### ISSUE TITLE
Using Custom Scrollbar instead of native Scrollbar

### ISSUE THREAD

**Issue by nizulzaim** [dixonandmoe/rellax#65]
Hi, is it possible to detect custom scrollbar or creating new option to bind to custom scrollbar rather than using native scrollbar. Maybe it can provide selector to some class or DOM rather than only binding it to `window`. Btw, nice to use this plugin. It is very easy to use.

**Comment by moeamaya** [comment]
Hey @nizulzaim thanks for the issue. I don't think this is within the scope of the lib.

We do have an open Pull Request that may solve your issue: https://github.com/dixonandmoe/rellax/pull/27.
