### ISSUE TITLE
GIF causes scroll stutter for firefox/edge

### ISSUE THREAD

**Issue by jobjp** [dixonandmoe/rellax#69]
When using click scroll and having GIFs on the webpage there is stutter on firefox/edge.

**Comment by moeamaya** [comment]
Thanks for reporting the issue.

Not sure how we can remedy this since it's a rendering/painting problem with browsers. But I'll keep this open so others can see it

**Comment by joelhoelting** [comment]
Also having this issue with multiple raster images while scrolling. The stuttering usually occurs after adding parallax to a third raster image. Would a possible fix be to create and destroy Rellax instances based on scroll position?

**Comment by moeamaya** [comment]
@joelhoelting Are these 3 raster images overlapping during parallax, or are they just 3 images separated and on the same page but not overlapping?

**Comment by joelhoelting** [comment]
@moeamaya. Please disregard my issue, it was being caused by something else.
