### ISSUE TITLE
Option to disable on mobile? 

### ISSUE THREAD

**Issue by iamdubx** [dixonandmoe/rellax#74]
Hi. Love this library on desktop. But in general I hate parallax on mobile devices due to wierd browser address bar behavior. Is there any tips how to disable rellax on mobile? I could detect mobile devices, but what next?

**Comment by nlemoine** [comment]
Please don't provide a way to handle this feature such as many libraries do. 

IMHO, the only requirement for any good library is to provide a `destroy` and `init` methods. It's then developer responsibility to handle the context where something happens or not. 

And there's many easy ways to achieve this : 
- For a resolution context, media queries with [`matchMedia`](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) or the help of a `matchMedia` wrapper such as [enquire.js](https://github.com/WickyNilliams/enquire.js). 
- For feature context, there's [Modernizr](https://github.com/Modernizr/Modernizr) or [feature.js](https://github.com/viljamis/feature.js/)
- And if you wanna target directly user agent, there's also some good libraries for this.

**Comment by moeamaya** [comment]
@p-realinho and others. What do you guys think? I'm personally okay with adding a boolean option and re-using the landscape check to detect mobile, but I want to hear other's opinions.

**Comment by iamdubx** [comment]
Well, I guess @nlemoine makes a good point. 
I don't see any methods to implicitly disable Rellax on mobile without bloating code (or how to detect mobile other ways?)
Maybe he is right. I need to do it myself and just remove `rellax` class, for example.

**Comment by p-realinho** [comment]
Yea, the feature can be useful in some cases, but at the same time I do agree with @nlemoine and the repo's KISS approach ... 
Maybe an example snippet on the readme would suffice?

**Comment by moeamaya** [comment]
Okay I think those are some good thoughts. I'll add some documentation to the README and close this issue later

**Comment by dp-thomas** [comment]
i think this one goes with [https://github.com/dixonandmoe/rellax/issues/58](url).
At least, I suggested this for disabling it on small viewports

**Comment by pietschm** [comment]
A quick, but not perfect, solution could be overwriting the transform for smaller devices like this:

`@media (max-width: 992px) {
    .rellax {
      transform: translate3d(0,0,0) !important;
    }
}`

**Comment by radiocity** [comment]
@iamdubx,  do lazy load of rellax.js with an init callback for screen.availWidth > 860px

**Comment by iamdubx** [comment]
@radiocity I want it loaded on Desktops with any screen width, for example.

**Comment by radiocity** [comment]
@iamdubx, okay. Make a lazy load with mobile device validation.
