### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by andrewtanchuk** [dixonandmoe/rellax#78]
Awesome parallax plugin 👍
Can I set the element horizontal scroll?

**Comment by susonwaiba** [comment]
you can't yet. But maybe it will be available in future updates!

**Comment by Alex360hd** [comment]
+1 for this. Horizontal scroll would be a very useful addition !

**Comment by bglaz** [comment]
@Alex360hd I made a quick and dirty horizontal version just by swapping all references of 'Y' to 'X' and 'Height' to 'Width', etc. I can make a fork and post it if you need.

**Comment by moeamaya** [comment]
We may be using this at some point soon, so hold tight. But for now try @bglaz idea!

**Comment by johanneslamers** [comment]
+1 for this! And passive event listeners for enhanced performance.

**Comment by kovtunos** [comment]
@bglaz How can I explain to particular HTML element that it must use horizontal parallax instead of vertical? Can't find proper data attributes in your solution.

**Comment by bglaz** [comment]
@kovtunos What are you looking to do exactly? The version I built is for panoramic scrolling websites, where the user scrolls left to right instead of up and down.

Are you looking to have elements move horizontally as the user scrolls vertically?

**Comment by kovtunos** [comment]
@bglaz Thanks for answering. 

> Are you looking to have elements move horizontally as the user scrolls vertically?

I thought that it should work like that.

**Comment by chasegiunta** [comment]
Just to echo @kovtunos... I was also hoping (and initially thought it was) horizontal movement upon vertical scrolling functionality.

**Comment by moeamaya** [comment]
I'm closing this issue for now. In Rellax v2 we'll let you add any type of transform you want including moving the elements horizontally.
