### ISSUE TITLE
How use rellax with simple image?

### ISSUE THREAD

**Issue by geosenna** [dixonandmoe/rellax#79]
Can I use this plugin to apply this rellax to simple image tag? Let's imagine a grid display with articles. I would just need the image to have a rellax effect.

I test but nothing happen, the style transform/translate is applied to the images, but i can't see anything moving...

thanks :)

**Comment by p-realinho** [comment]
Hi! Thanks for using Rellax. :)

That's strange! Could you share a link, or post it on CodePen or something so we can take a look at the code pls?

**Comment by susonwaiba** [comment]
@geosenna 
It might be you have done `!important` or something as rellax uses inline css! Else you may check demo [https://dixonandmoe.com/rellax/](https://dixonandmoe.com/rellax/) . Rellax adds inline css `transform: translate3d()` where ever you add `rellax` css class according to demo! _(or you may use own css class as per requirement)_
