### ISSUE TITLE
(IE10) SCRIPT5007: Unable to get value of the property "rellaxPercentage": object is null or undefined

### ISSUE THREAD

**Issue by radiocity** [dixonandmoe/rellax#81]
Getting `SCRIPT5007: Unable to get value of the property "rellaxPercentage": object is null or undefined` in Internet Explorer 10 at rellax.min.js (1,1033).
```html
<div class="background rellax" data-rellax-speed="-4"></div>
```
```js
if (document.querySelectorAll('.rellax').length > 0 && (screen.width > 860)) {
    include( CONFIG.BASE_URL + "rellax.min.js", function() {
        var rellax = new Rellax('.rellax');
    });
}
```
rellax.min.js loaded successfully

**Comment by radiocity** [comment]
Error was caused by another plugin

**Comment by jesseyuen** [comment]
@radiovity - I getting this error in ie10 too. What plugin was causing the issue for you?

**Comment by radiocity** [comment]
It was caused by async script loader.
