### ISSUE TITLE
Pixel perfect transforms

### ISSUE THREAD

**Issue by glafarge** [dixonandmoe/rellax#84]
Since pull request #50 we are unable to have pixel perfect values.
Round to one decimal should be the default behaviour for performance issues but we should have the capability to get pixel perfect values.
This is especially needed when the parallax is applied on small paragraphs (it avoids blurry texts).

I also made a pull request if needed (i increased decimal precision to 2 decimals for default behaviour).

**Comment by moeamaya** [comment]
Thanks for the update. I haven't had a chance to experience this issue, but I'll take a look in a bit. 

So far on the demo page (https://dixonandmoe.com/rellax/) it seems to work pretty well for me, but I'm on Chrome/Safari on a Mac, so it's likely worse on Windows or Linux setup

**Comment by glafarge** [comment]
Sure ! Font rendering on windows is ~~a little bit~~ different.
Thank you for your nice work by the way 👍

**Comment by moeamaya** [comment]
@glafarge Did the PR break the pixel perfect transforms?

**Comment by glafarge** [comment]
@moeamaya no ! Everything is ok :)
My mistake.... "Font rendering WAS different"
