### ISSUE TITLE
Scale parallax option?

### ISSUE THREAD

**Issue by hackuun** [dixonandmoe/rellax#87]
What do you guys think of adding scale transform option?

**Comment by moeamaya** [comment]
In Rellax v2.0, we'll add the ability to use any transform method you want! But that said we're not planning on starting that development until April 2018.

**Comment by yairEO** [comment]
I've re-written the whole code of Rellax (took a few hours) and now you can do whatever you want in the callback function. (see the example page in my fork)

[Link to the fork](https://github.com/yairEO/rellax)

### Example:

    var rellax = new Rellax('.rellax', {
        // add "blur" as you scroll down
        callback: function( instance ) {
            var visiblePercentage = 1,
                topOffset = instance.blocks[0].node.getBoundingClientRect().top, // pixels which aren't visible anymore
                parentHeight = instance.blocks[0].node.clientHeight;

                if( topOffset < 0 )
                  visiblePercentage = (parentHeight + topOffset) / parentHeight;

                instance.blocks[0].node.style.filter = `blur(${10 - 10 * visiblePercentage}px)`;
        }
    });
