### ISSUE TITLE
Issues regarding smoothness of parallax effect

### ISSUE THREAD

**Issue by jr-cologne** [dixonandmoe/rellax#90]
Hi there!

First of all, thanks for your work. This is a really good library!

I encountered some issues regarding the smoothness of the parallax effect.
The elements which have the parallax effect attached are jumping around a bit and do not move smoothly.

After trying out some things I believe that the behavior somehow depends on the speed of the element you declare with the `data-rellax-speed` attribute since elements with speed `-7` are for example jumping around much more than elements with speed `7`. So, it seems like the lower the speed, the worse the problem.

In order to illustrate the problem a bit, I have created a Pen which has four elements with different speeds. Furthermore, I have recorded a short clip to better clarify what I mean with "jumping around".

Link to the Pen: https://codepen.io/jr-cologne/pen/jagaMK
Link to the video: https://streamable.com/rxghi

I tested the whole thing in the following browsers:
- Chrome version 63.0.3239.84 64 bit (working fine)
- Chrome Mobile version 63.0.3239.107 (affected)
- Firefox 57.0.2 64 bit (a bit worse than Chrome, but still reasonable)
- Edge 16.16299 (definitely affected)
- IE 11.64.16299.0 (same as Edge)

Thank you in advance for any efforts you put into this issue!

Best regards from Germany,
@jr-cologne

**Comment by p-realinho** [comment]
Hey!
And thank you for using it. 🙂

I took a quick look at the pen and I'm also experiencing the same issue.
Running Chrome 63.0.3239.84 (64-bit) on Windows 10.

I must say tho, first time seeing this problem, even more, on such a simple use case...
No suggestions atm, but I'll try to look into it later.

**Comment by jr-cologne** [comment]
Hi @p-realinho,
Thank you for your reply.

It's kind of weird that your are experiencing the issue in the exact same browser and OS, where I didn't notice anything.

Anyway, might has something to do with the new updates to Chrome, Firefox, etc.
I never had those issues before, too.

**Comment by jr-cologne** [comment]
@p-realinho Any progress? Did you already take a closer look at the issue?

**Comment by p-realinho** [comment]
Sorry. To be honest, I forgot 😅

Ok, so, I found a small workaround that seems to be working for me (tested in Firefox and Chrome).
```css
.container::before{
	content: ' ';
	position: fixed;
}
```

Still, not sure why this happens, or how to solve it, but as far as I can tell, it's not an issue with Rellax _per se_, it's more likely related to the browsers' rendering engines...

**Comment by jr-cologne** [comment]
Ok, no problem. :D

I will test this workaround and then get back to you. Not sure if I have the time for it today or tomorrow, but you will get an answer as soon as possible.

**Comment by jr-cologne** [comment]
Hi,
sorry for the late reply.

Your workaround has basically changed nothing for me.

Just to be on the save side: Did I implement the workaround the same way like you?

I updated the Pen: https://codepen.io/jr-cologne/pen/jagaMK

**Comment by p-realinho** [comment]
Yup, it's implemented correctly.
It's working fine for me.

Guess I'm out of options here. 😕

**Comment by jr-cologne** [comment]
Me too. Don't know what I should do now. :(

**Comment by p-realinho** [comment]
Can I ask what the specific use case is?
Maybe I can help you find a solution...
For example, you could try to use it on a `position: fixed` element with a higher `rellax-speed` (closer to zero, I mean), instead of setting the speed to `-7` on a `position: static / relative / absolute ...` element.

**Comment by jr-cologne** [comment]
The element I want to animate/give the parallax effect is a header which is part of a hero background image section.

I don't think that changing the position property is possible in my case, but I will check that.
I can also give you further details about my use case later.

Thanks for your help by the way...

**Comment by jr-cologne** [comment]
Ok, since I don't really want to upload the website of someone else, you can actually see the whole thing in action by visiting the [homepage of my own website](https://jr-cologne.de/).

There I use this library to give a container with a heading and a CTA a parallax effect which is in front of a hero background image. The speed is `-4` and I get the issue in Edge and IE.

Setting the position to fixed is not an option.

**Comment by jr-cologne** [comment]
I would need to take a closer look and test it in all browsers again, but I am convinced that the issue is still existing.

I am actually also experiencing this with a normal jQuery implementation, so it's probably not the fault of your library.

**Comment by justintime4tea** [comment]
Might want to try pure CSS parallaxing using perspective, preserve3d and translating on Z.. Due to Firefoxs multi-thread rendering and relying on scroll update events, I get janky issues. What I have works fine in Chrome but being a developer profile I'm aiming for complete cross-browser support. I've tried so many JS based parallaxing solutions my head is spinning and pure CSS was the only way to get the results I want on all the browsers. I do love this library though. Pure CSS parallaxing isn't bad if you tweak the scaling right so that text is close enough to a pixel region that it doesn't blur.

**Comment by jr-cologne** [comment]
@justintime4tea Thank you for this recommendation. I will definitely take a look at it. Never heard of this before.

**Comment by moeamaya** [comment]
@jr-cologne CSS parallax are great, but have their own issues, namely crazy HTML structural requirements. [Keith Clark's work](https://keithclark.co.uk/articles/pure-css-parallax-websites/) is the reason I created Rellax, because my code was so hard adjust. 

If you do need slower parallax, unfortunately Rellax isn't the right solution. I might check out Stellar or try the CSS version to see if they work for you. For now closing this issue.
