### ISSUE TITLE
Problem on destroy

### ISSUE THREAD

**Issue by lateek35** [dixonandmoe/rellax#91]
I think the `destroy()` method, is misleading. Currently it's seems to reset the style to the originals values and pause the parallax and that's all. Listener and loop are still active. I think it's an issue for someone who want to destroy et init instance very often.

I think it could leads to some cpu consumption's problems for a huge amount of destroy.
For exemple one of the side effect is that resize event is still fired. So when I destroy Rellax and then resize my window, the resize function call `animate()` and my element get moved even though I destroyed it before.

By the way I think 
```
window.addEventListener('resize', function(){
    animate();
});
```
should probably be 
```
window.addEventListener('resize', function(){
   if( pause === false ) animate();
});
```

**Comment by brian-gonzalez** [comment]
Seconding this, I'd like to disable Rellax when reaching certain breakpoints but re-enable when exiting those. Because animate() is on resize the transform property gets reapplied to the elements even after a destroy() is called.

**Comment by moeamaya** [comment]
Open to Pull Request on this one. Thanks guys

**Comment by yairEO** [comment]
I've forked the code and re-wrote much of it and also fixed that problem:

https://github.com/yairEO/rellax

It was shouting for attention the moment I looked at the code.
No body should leave an un-needed `window` event binded without properly unbinding it in some `destory` method.

**Comment by moeamaya** [comment]
Fixed with latest merge
