### ISSUE TITLE
The elements you're trying to select don't exist. At new g (rellax.min.js:1)

### ISSUE THREAD

**Issue by hitaspdotnet** [dixonandmoe/rellax#94]
Hi,
I want try using Rellax in my MVC application at once of my views.
So I add the rellax.js script link (without bundling) and few lines script for rellax in `@section scripts{<--->}` at the target view. 
Now when I trying to run console response a throw error

>  Uncaught Error: The elements you're trying to select don't exist.
>     at new g (rellax.min.js:1)

I read similar issue but I used rellax.js and tags in one view without bundling
Here is my .cshtml
```
    <div class="rellax-header rellax-header-sky" data-rellax-speed="-8" style="transform: translate3d(0px, 421px, 0px);">
        <div class="page-header-image" style="background-image:url(@backPath)">
        </div>
    </div>
    <div class="rellax-header rellax-header-buildings" data-rellax-speed="0" style="transform: translate3d(0px, 0px, 0px);">
        <div class="page-header-image page-header-city" style="background-image:url(@imagePath)">
        </div>
    </div>
    <div class="rellax-text-container rellax-text" style="transform: translate3d(0px, 128px, 0px);">
        <h1 class="h1-seo" data-rellax-speed="-2">Test</h1>
        <div class="pro">PRO</div>
    </div>
@section Scripts {
<script src="~/js/plugins/rellax.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            if ($(window).width() >= 991) {
                setTimeout(function () {
                    var rellax = new Rellax('.rellax', {
                        center: true
                    });
                }, 5000);

                var rellaxHeader = new Rellax('.rellax-header');
                var rellaxText = new Rellax('.rellax-text');
            }
        });
    </script>
}
```
Any Idea please?!

**Comment by tomhoad** [comment]
Your JS is looking for the class `.rellax`, which isn't added to any element in your template.

Add `rellax` to your template:

`rellax rellax-text-container rellax-text`

Although, I don't think you need to instantiate 3 times anyway. Just use `data-rellax-speed` on each element to vary the parallax speed.

**Comment by luongvanphuc** [comment]
I agree, but personally I think it should not be an "Uncaught Error", because it will stop the below scripts from excuting, which might cause the pages to have other unexpected errors.
For now as a workaround, I have to check if there is any `.rellax` element or not.

**Comment by 01ivr3** [comment]
Seriously

**Comment by moeamaya** [comment]
@luongvanphuc @01ivr3 There are several opinions regarding good coding practices, but I do believe that Rellax is a "nice to have" and therefore I enforce my own opinion which is that we throw an "Uncaught Error"

While this is an annoyance, the real issue resides in your own code since the `.rellax` element doesn't exist and therefore the script should not run. As workaround as I'm sure you've noticed is that you have to add an `if` statement, which again is good coding practice.

**Comment by mattrittman** [comment]
I'm having the same problem, and completely confused as to why it's not working. Can someone help? Here's my page: http://www.mattrittman.com/new-media-header/
