### ISSUE TITLE
Use scroll from other element.

### ISSUE THREAD

**Issue by jvrdom** [dixonandmoe/rellax#97]
Hi, i'm using this library and I have a question if is posible, to is possible to contain the parallax effect inside a container? that the top of the scroll has to be the top of a div.

Thanks!

**Comment by p-realinho** [comment]
Hey!
I've seen you commented on #27. Is that the behavior you were lookin for?

**Comment by jvrdom** [comment]
@p-realinho yes, that's what I looking for.
