### ISSUE TITLE
Incorrect positionning with Wordpress and Page Builder Elementor

### ISSUE THREAD

**Issue by EmeraudeIzenah** [dixonandmoe/rellax#99]
Hi,

Thank's for this plugin !

I'm using rellax for a wordpress website with the page builder Elementor. First, it looks fine but when I force reload (ctrl + f5) there is a problem with the position of my elements. 

Link : https://www.wao-artistic.fr/support-artistique-wao/
Press ctrl + f5 and f5 many times to reproduce the problem.

I'm using the latest version of Chrome.

I believe there is a conflict with Elementor and Rellax (because I didn't have the problem before using the page builder...)

I hope you can help me fixing this problem...

Thank's !

**Comment by p-realinho** [comment]
Hey! Thanks for using it! 🙂 
Could you please try the solution for #52 and see if solves it?
Thanks.

**Comment by EmeraudeIzenah** [comment]
Oh yes, it seems to work ! Sorry, I thought of having searched enough but I had not seen the topic #52 :(

Thank you for your help !!

**Comment by p-realinho** [comment]
No problem!
Glad you solved it. 🙂

**Comment by p-realinho** [comment]
(Btw, could you close the issue please? Thanks.)
